/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://2ytn6wqnobewnorcnhwdxg5key.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l7iurjcktzdoviuxblku4fhdzi",
    "aws_cognito_identity_pool_id": "ap-southeast-1:93d6cf29-e6b2-49b0-92ae-96397b8af1fd",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_I7nKiAdPg",
    "aws_user_pools_web_client_id": "2q3g6p0k3ugcgfgn3ipqs2ocfq",
    "oauth": {}
};


export default awsmobile;
